### ISSUE TITLE
Empty range maps for a few species

### ISSUE THREAD

**Issue by fabeit** [MegaPast2Future/PHYLACINE_1.2#3]
Hello, it's always me :)
Apologies in advances if I have missed some information in the paper.
I have found 18 species in the Present natural ranges that do not have any range, basically all the values in the raster are 0. Is this a known issues? These are the species:

Alouatta seniculus     
Dasyprocta ruatanica  
  Geocapromys thoracatus 
Microtus abbreviatus  
  Neotoma bryanti        
Oryzomys nelsoni      
  Phalanger alexandrae   
Piliocolobus pennantii
  Pteropus aldabrensis   
Pteropus howensis     
 Pteropus mariannus     
Pteropus molossinus   
 Pteropus pelewensis    
Pteropus pilosus      
 Pteropus pselaphon     
Pteropus tokudae      
 Pteropus ualanus       
Sylvilagus graysoni

Thanks in advance.

**Comment by jarsc568** [comment]
Hi @fabeit - thanks again for your enquiry. 

We believe there should be only 15 species that do not have present-natural ranges; only two of them are on your list (_Alouatta seniculus_ and _Piliocolobus pennantii_). The metadata in the paper addresses the reason for there being no present-natural ranges for these species near the end of the "Current ranges" section. To find out which species should have missing present-natural range maps, one way is to look at the "metadata.csv" file found here: "PHYLACINE_1.2/Data/Ranges/ Spatial_metadata.csv". If you look at the column "Number.Cells.Present.Natural.Range", you can sort and see the species with 0 cells. They are listed below:

Binomial.1.2
--
Alouatta_seniculus
Cebus_aequatorialis
Cebus_brunneus
Cebus_capucinus
Cebus_cesarae
Cebus_cuscinus
Cebus_malitiosus
Cebus_versicolor
Gazella_marica
Miniopterus_africanus
Pattonomys_punctatus
Piliocolobus_pennantii
Pithecia_chrysocephala
Pithecia_milleri
Pithecia_vanzolinii

I also checked manually for the species in **your list** by loading the rasters and they were in PHYLACINE v1.2 that was loaded today (apart from the two species with 0 cells).
