### ISSUE TITLE
Body mass for Sinomegaceros ordosianus

### ISSUE THREAD

**Issue by fabeit** [MegaPast2Future/PHYLACINE_1.2#5]
Body mass for this species is 404.3 g. It seems it should be somewhere near the sister species S. yabei.

**Comment by rasmus87** [comment]
Thank you for bringing this to our attention. The species was accidentally given the body mass of Thrichomys laurentius during a manual data entry. As noted in our [Roadmap](https://github.com/MegaPast2Future/PHYLACINE_1.2#view-our-road-map), we are aware of the mistake, and will be pushing a fix for this in the upcoming update. It will be phylogenetically imputed, and will likely get a mass very close to it's sister species as you say.
