### ISSUE TITLE
Male or female body mass?

### ISSUE THREAD

**Issue by fabeit** [MegaPast2Future/PHYLACINE_1.2#6]
Hello, I have read through the metadata pdf but I can't find any direct information if the reported body mass are for the average male or female, or an average of both. I realize that 60% of species mass was estimated using Smith et al. 2003, but it would be important to have a clear indication, as sexual dimorphism can be large in mammals.

**Comment by jarsc568** [comment]
Hi Fabiet, as mentioned in the metadata, the body masses came from a large number of literature sources, with about 60% of the species were given values from the Mass of Mammals database (V.4.1) (Smith et al. 2003). In total, the PHYLACINE contains weights reported from the Mass of Mammals database or other sources for 4861 species. For another 768 species, masses were estimated by morphological correlates or based on a relative that a species was said to resemble in size. Masses for the remaining 202 species were estimated by phylogenetic imputation and clearly labelled. 

At this stage, we will not provide an indication for the sex- we note that it is not always provided. If you do find the sex for species in your studies, feel free to send it and we might include it in a future update.
