### ISSUE TITLE
Dasyurus maculatus body mass discrepancy

### ISSUE THREAD

**Issue by ejlundgren** [MegaPast2Future/PHYLACINE_1.2#7]
Phylacine reports the Tiger Quolls body mass 5.5kg from Smith, F. A., et al. 2003. Body mass of late Quaternary mammals. Ecology 84:3403 (Updated Version 4.1 obtained from senior author).

This puts them nearly twice the size of a house cat, which is not true and would raise eyebrows among most ecologists. I couldn’t find references for Smith et al’s body mass but found this paragraph from Jones et al., 2001 - https://www.researchgate.net/publication/316142574_Dasyurus_maculatus.

“Sexual size dimorphism is pronounced. Adult males (mean = 3.5 kg, n = 10) of the southern subspecies, D. m. maculatus, are twice the mass of adult females (mean = 1.8 kg, n = 9) and have stronger canines and thicker necks (Jones 1995). Maximum sizes are 7 and 4 kg for males and females, respectively (Settle 1978).”

My best guess is that Smith et al., 2003 took their body sizes from Settle 1978 (7+4/2=5.5kg).  I’m not sure how you are dealing with sexual dimorphism, but it may be worth taking the sample size weighted average of the measures from the Jones paper above. Body size information on the species is, otherwise, surprisingly scant.

**Comment by rasmus87** [comment]
Moved to issue in the development repository for next PHYLACINE release.
